version: '3'
services:
  solr:
    image: solr
    build: 
      context: .
      dockerfile: Dockerfile.solr
    ports:
     - "8983:8983"
    volumes:
      - solr-data:/var/solr
    command: >
      sh -c "precreate-core document; exec solr -f"
  postgres:
    image: postgres
    ports:
     - "54321:5432"
    environment:
      POSTGRES_USER: bpkb
      POSTGRES_PASSWORD: P@ssw0rd!
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  solr-data: 
  postgres-data: