version: '3'
services:
  solr1:
    image: solr
    container_name: solr-polda
    build: 
      context: .
      dockerfile: Dockerfile.solr
    ports:
     - "8983:8983"
    restart: always
    volumes:
      - solr-data:/var/solr
    command: >
      sh -c "precreate-core document; cp managed-schema.xml /var/solr/data/document/conf/managed-schema; exec solr -f"
  solr2:
    image: solr
    container_name: solr-polri
    build: 
      context: .
      dockerfile: Dockerfile.solr
    ports:
     - "9999:8983"
    restart: always
    volumes:
      - solr2-data:/var/solr
    command: >
      sh -c "precreate-core document; cp managed-schema.xml /var/solr/data/document/conf/managed-schema; exec solr -f"
  postgres:
    image: postgres
    container_name: postgres
    ports:
     - "54321:5432"
    restart: always
    environment:
      POSTGRES_USER: bpkb
      POSTGRES_PASSWORD: P@ssw0rd!
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  solr-data: 
  solr2-data: 
  postgres-data: