version: '3'
services:
  solr-polda:
    image: solr
    container_name: solr-polda
    build: 
      context: .
      dockerfile: Dockerfile.solr
    ports:
     - "8981:8983"
    restart: always
    volumes:
      - solr-data-polda:/var/solr
    command: >
      sh -c "precreate-core document; cp managed-schema.xml /var/solr/data/document/conf/managed-schema; exec solr -f"
  solr-polri:
    image: solr
    container_name: solr-polri
    build: 
      context: .
      dockerfile: Dockerfile.solr
    ports:
     - "8980:8983"
    restart: always
    volumes:
      - solr-data-polri:/var/solr
    command: >
      sh -c "precreate-core document; cp managed-schema.xml /var/solr/data/document/conf/managed-schema; exec solr -f"
  postgres-polda:
    image: postgres
    container_name: postgres-polda
    ports:
     - "54321:5432"
    restart: always
    environment:
      POSTGRES_USER: bpkb
      POSTGRES_PASSWORD: P@ssw0rd!
    volumes:
      - postgres-data-polda:/var/lib/postgresql/data
  postgres-polri:
    image: postgres
    container_name: postgres-polri
    ports:
     - "54320:5432"
    restart: always
    environment:
      POSTGRES_USER: bpkb
      POSTGRES_PASSWORD: P@ssw0rd!
    volumes:
      - postgres-data-polri:/var/lib/postgresql/data
volumes:
  -polda-polda: 
  solr-data-polri: 
  postgres-data-polda:
  postgres-data-polri: