version: '3'
services:
  admin-service-polri:
    image: admin-service-polri
    build: 
      context: .
      dockerfile: Dockerfile.admin-service
    restart: always
    expose:
      - "7070"
    ports:
      - "6070:7070"
  fp-service-polri:
    image: fp-service-polri
    build: 
      context: .
      dockerfile: Dockerfile.fp-service
    restart: always
    expose:
      - "7071"
    ports:
      - "6071:7071"
    volumes:
      - ~/uploads-polri:/uploads
  scheduler-service-polri:
    image: scheduler-service-polri
    build: 
      context: .
      dockerfile: Dockerfile.scheduler-service
    restart: always
    expose:
      - "7072"
    ports:
      - "6072:7072"
  frontend-polri:
    image: frontend-polri
    build: 
      context: .
      dockerfile: Dockerfile.frontend
    restart: always
    expose:
      - "80"
      - "443"
    ports:
      - "6080:80"
      - "60443:443"