version: '3'
services:
  admin-service-polda:
    image: admin-service-polda
    build: 
      context: .
      dockerfile: Dockerfile.admin-service
    restart: always
    expose:
      - "7070"
    ports:
      - "7070:7070"
  fp-service-polda:
    image: fp-service-polda
    build: 
      context: .
      dockerfile: Dockerfile.fp-service
    restart: always
    expose:
      - "7071"
    ports:
      - "7071:7071"
    volumes:
      - ~/uploads-polda:/uploads
  scheduler-service-polda:
    image: scheduler-service-polda
    build: 
      context: .
      dockerfile: Dockerfile.scheduler-service
    restart: always
    expose:
      - "7072"
    ports:
      - "7072:7072"
  frontend-polda:
    image: frontend-polda
    build: 
      context: .
      dockerfile: Dockerfile.frontend
    restart: always
    expose:
      - "80"
      - "443"
    ports:
      - "7080:80"
      - "8443:443"