version: '3'
services:
  admin-service:
    image: admin-service
    build: 
      context: .
      dockerfile: Dockerfile.admin-service
    ports:
      - "7070:7070"
  fp-service:
    image: fp-service
    build: 
      context: .
      dockerfile: Dockerfile.fp-service
    ports:
      - "7071:7071"
  frontend:
    image: frontend
    build: 
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"