version: '3'
services:
  # Admin Service
  admin-service:
    image: admin-service
    build: 
      context: .
      dockerfile: Dockerfile.admin-service
    expose:
      - "7070"
    ports:
      - "7070:7070"
      
  # FP Service
  fp-service:
    image: fp-service
    build: 
      context: .
      dockerfile: Dockerfile.fp-service
    expose:
      - "7071"
    ports:
      - "7071:7071"
    volumes:
      - /root/bpkb/uploads:/uploads

  # Frontend
  frontend:
    image: frontend
    build: 
      context: .
      dockerfile: Dockerfile.frontend
    expose:
      - "80"
    ports:
      - "8888:80"